package entity;
// Generated Jan 24, 2017 7:49:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dan generated by hbm2java
 */
public class Dan  implements java.io.Serializable {


     private Long idDan;
     private Festival festival;
     private Integer redniBroj;
     private int brojUlaznica;
     private Set izvodjacs = new HashSet(0);
     private Set rezervacijas = new HashSet(0);

    public Dan() {
    }

	
    public Dan(Festival festival, int brojUlaznica) {
        this.festival = festival;
        this.brojUlaznica = brojUlaznica;
    }
    public Dan(Festival festival, Integer redniBroj, int brojUlaznica, Set izvodjacs, Set rezervacijas) {
       this.festival = festival;
       this.redniBroj = redniBroj;
       this.brojUlaznica = brojUlaznica;
       this.izvodjacs = izvodjacs;
       this.rezervacijas = rezervacijas;
    }
   
    public Long getIdDan() {
        return this.idDan;
    }
    
    public void setIdDan(Long idDan) {
        this.idDan = idDan;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Integer getRedniBroj() {
        return this.redniBroj;
    }
    
    public void setRedniBroj(Integer redniBroj) {
        this.redniBroj = redniBroj;
    }
    public int getBrojUlaznica() {
        return this.brojUlaznica;
    }
    
    public void setBrojUlaznica(int brojUlaznica) {
        this.brojUlaznica = brojUlaznica;
    }
    public Set getIzvodjacs() {
        return this.izvodjacs;
    }
    
    public void setIzvodjacs(Set izvodjacs) {
        this.izvodjacs = izvodjacs;
    }
    public Set getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set rezervacijas) {
        this.rezervacijas = rezervacijas;
    }




}


