package entity;
// Generated Jan 24, 2017 8:19:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Izvodjac generated by hbm2java
 */
public class Izvodjac  implements java.io.Serializable {


     private Long idIzv;
     private Dan dan;
     private Festival festival;
     private String naziv;
     private Date vremeOd;
     private Date vremeDo;

    public Izvodjac() {
    }

	
    public Izvodjac(Dan dan, Festival festival) {
        this.dan = dan;
        this.festival = festival;
    }
    public Izvodjac(Dan dan, Festival festival, String naziv, Date vremeOd, Date vremeDo) {
       this.dan = dan;
       this.festival = festival;
       this.naziv = naziv;
       this.vremeOd = vremeOd;
       this.vremeDo = vremeDo;
    }
   
    public Long getIdIzv() {
        return this.idIzv;
    }
    
    public void setIdIzv(Long idIzv) {
        this.idIzv = idIzv;
    }
    public Dan getDan() {
        return this.dan;
    }
    
    public void setDan(Dan dan) {
        this.dan = dan;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getVremeOd() {
        return this.vremeOd;
    }
    
    public void setVremeOd(Date vremeOd) {
        this.vremeOd = vremeOd;
    }
    public Date getVremeDo() {
        return this.vremeDo;
    }
    
    public void setVremeDo(Date vremeDo) {
        this.vremeDo = vremeDo;
    }




}


