package entity;
// Generated Jan 24, 2017 8:19:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String username;
     private String password;
     private String ime;
     private String prezime;
     private String telefon;
     private String email;
     private Boolean active;
     private String tipKorisnika;
     private boolean blokRez;
     private Date vremePristupa;
     private Set ocenas = new HashSet(0);
     private Set rezervacijas = new HashSet(0);
     private Set porukas = new HashSet(0);
     private Set komentars = new HashSet(0);
     private Set medias = new HashSet(0);

    public Korisnik() {
    }

	
    public Korisnik(String username, String password, boolean blokRez) {
        this.username = username;
        this.password = password;
        this.blokRez = blokRez;
    }
    public Korisnik(String username, String password, String ime, String prezime, String telefon, String email, Boolean active, String tipKorisnika, boolean blokRez, Date vremePristupa, Set ocenas, Set rezervacijas, Set porukas, Set komentars, Set medias) {
       this.username = username;
       this.password = password;
       this.ime = ime;
       this.prezime = prezime;
       this.telefon = telefon;
       this.email = email;
       this.active = active;
       this.tipKorisnika = tipKorisnika;
       this.blokRez = blokRez;
       this.vremePristupa = vremePristupa;
       this.ocenas = ocenas;
       this.rezervacijas = rezervacijas;
       this.porukas = porukas;
       this.komentars = komentars;
       this.medias = medias;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getTipKorisnika() {
        return this.tipKorisnika;
    }
    
    public void setTipKorisnika(String tipKorisnika) {
        this.tipKorisnika = tipKorisnika;
    }
    public boolean isBlokRez() {
        return this.blokRez;
    }
    
    public void setBlokRez(boolean blokRez) {
        this.blokRez = blokRez;
    }
    public Date getVremePristupa() {
        return this.vremePristupa;
    }
    
    public void setVremePristupa(Date vremePristupa) {
        this.vremePristupa = vremePristupa;
    }
    public Set getOcenas() {
        return this.ocenas;
    }
    
    public void setOcenas(Set ocenas) {
        this.ocenas = ocenas;
    }
    public Set getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set rezervacijas) {
        this.rezervacijas = rezervacijas;
    }
    public Set getPorukas() {
        return this.porukas;
    }
    
    public void setPorukas(Set porukas) {
        this.porukas = porukas;
    }
    public Set getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set komentars) {
        this.komentars = komentars;
    }
    public Set getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set medias) {
        this.medias = medias;
    }




}


