package entity;
// Generated Jan 24, 2017 8:19:08 AM by Hibernate Tools 4.3.1



/**
 * Link generated by hbm2java
 */
public class Link  implements java.io.Serializable {


     private Long idLink;
     private Festival festival;
     private String url;

    public Link() {
    }

    public Link(Festival festival, String url) {
       this.festival = festival;
       this.url = url;
    }
   
    public Long getIdLink() {
        return this.idLink;
    }
    
    public void setIdLink(Long idLink) {
        this.idLink = idLink;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


