package entity;
// Generated Jan 24, 2017 8:19:08 AM by Hibernate Tools 4.3.1



/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Long idMed;
     private Festival festival;
     private Korisnik korisnik;
     private String url;
     private String slikaVideo;
     private String status;

    public Media() {
    }

	
    public Media(Festival festival) {
        this.festival = festival;
    }
    public Media(Festival festival, Korisnik korisnik, String url, String slikaVideo, String status) {
       this.festival = festival;
       this.korisnik = korisnik;
       this.url = url;
       this.slikaVideo = slikaVideo;
       this.status = status;
    }
   
    public Long getIdMed() {
        return this.idMed;
    }
    
    public void setIdMed(Long idMed) {
        this.idMed = idMed;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getSlikaVideo() {
        return this.slikaVideo;
    }
    
    public void setSlikaVideo(String slikaVideo) {
        this.slikaVideo = slikaVideo;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


