package entity;
// Generated Jan 24, 2017 7:49:35 AM by Hibernate Tools 4.3.1



/**
 * Ocena generated by hbm2java
 */
public class Ocena  implements java.io.Serializable {


     private Long idOc;
     private Festival festival;
     private Korisnik korisnik;
     private Byte ocena;

    public Ocena() {
    }

    public Ocena(Festival festival, Korisnik korisnik, Byte ocena) {
       this.festival = festival;
       this.korisnik = korisnik;
       this.ocena = ocena;
    }
   
    public Long getIdOc() {
        return this.idOc;
    }
    
    public void setIdOc(Long idOc) {
        this.idOc = idOc;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Byte getOcena() {
        return this.ocena;
    }
    
    public void setOcena(Byte ocena) {
        this.ocena = ocena;
    }




}


