package entity;
// Generated Jan 24, 2017 7:49:35 AM by Hibernate Tools 4.3.1



/**
 * Poruka generated by hbm2java
 */
public class Poruka  implements java.io.Serializable {


     private Long idPor;
     private Festival festival;
     private Korisnik korisnik;
     private String sadrzaj;
     private String status;

    public Poruka() {
    }

	
    public Poruka(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public Poruka(Festival festival, Korisnik korisnik, String sadrzaj, String status) {
       this.festival = festival;
       this.korisnik = korisnik;
       this.sadrzaj = sadrzaj;
       this.status = status;
    }
   
    public Long getIdPor() {
        return this.idPor;
    }
    
    public void setIdPor(Long idPor) {
        this.idPor = idPor;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


